[package]
name = "cl-log"
version = "1.0.0"
edition = "2024"

[dependencies]
log = { version = "0.4.26", features = ["std"] }
parking_lot = "0.12.3"
chrono = "0.4.40"
bitflags = "2.9.0"
backtrace = "0.3.74"
colored = "3.0.0"
